# Generated by Django 4.2.5 on 2024-01-12 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
