# Generated by Django 4.2.5 on 2024-04-15 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0019_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=5.0, verbose_name="Оценка"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.SmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
