# Generated by Django 4.2.5 on 2024-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="telegramclient",
            name="TelegramCli_user_id_2f24c9_idx",
        ),
        migrations.RemoveField(
            model_name="telegramclient",
            name="client_id",
        ),
        migrations.AlterField(
            model_name="telegramclient",
            name="chat_id",
            field=models.PositiveIntegerField(
                db_index=True, verbose_name="Ид телеграм чата"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramclient",
            index=models.Index(
                fields=["user", "chat_id"], name="TelegramCli_user_id_662ede_idx"
            ),
        ),
    ]
